# Force dep to vendor the code generators, which aren't imported just used at dev time.
required = [
  "knative.dev/test-infra/scripts",
  "knative.dev/test-infra/tools/dep-collector",
]

[prune]
  go-tests = true
  non-go = true
  unused-packages = true

[[prune.project]]
  name = "knative.dev/test-infra"
  non-go = false
