kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: knative-eventing-operator
  namespace: knative-eventing
subjects:
- kind: ServiceAccount
  name: knative-eventing-operator
roleRef:
  kind: Role
  name: knative-eventing-operator
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: knative-eventing-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: knative-eventing-operator
subjects:
- kind: ServiceAccount
  name: knative-eventing-operator
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: knative-eventing-operator-aggregated
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: knative-eventing-operator-aggregated
subjects:
- kind: ServiceAccount
  name: knative-eventing-operator
  namespace: default
